branches:
  only:
  - feature-se2021
language: python
python:
 - "3.6"
 - "3.7"
 - "3.8"
 - "3.9"
install:
  - pip install -r requirements.txt
#Run Tests
script:
  - coverage run --source=./whun_helper test/* pytest && coverage report